Force function application before returning extraBuiltins
Before this commit builtins.extraBuiltins couldn't be used without
manually introducing strictness via seq or let binding.

The error nix reported was

```
error: value is a function application while a set was expected
```